name: Sync Gitee → GitHub
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git mirror sync
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GH_TOKEN: ${{ github.TOKEN }}
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror@example.com"
          # 设置git凭证助手，把github token注入
          git config --global credential.helper '!f() { echo "username=token"; echo "password=$GH_TOKEN"; }; f'

          git clone --bare "https://${GITEE_TOKEN}@gitee.com/jixukong/jieyou-embed-board.git" ./mirror.git
          cd ./mirror.git

          git remote add github "https://github.com/XukongJi/embed-board.git"
          git push --mirror github
