name: Sync Gitee → GitHub
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: sync gitee to github
        uses: yanglbme/gitee-mirror-github@main
        with:
          gitee_repo: jixukong/jieyou-embed-board
          github_repo: XukongJi/embed-board
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITHUB_TOKEN: ${{ github.TOKEN }}
